### ISSUE TITLE
Using the script without Nautilus

### ISSUE THREAD

**Issue by JeromeO** [remjg/AMCtoOwncloud#1]
Hi,
is there anyway to use this script without using Nautilus, but using the command line ?
I keep getting "ERROR: no files/folders provided neither selected in Nautilus".
Thank you

**Comment by remjg** [comment]
Bonjour !

Je me permets une réponse en français. Oui c'est possible et sûrement pas très difficile à ajouter. Je peux regarder à la Toussaint. En attendant, il faudrait sûrement remplacer à la main à la fin du script :

    amcsend = AMCtoOwncloud()

par :

    amcsend = AMCtoOwncloud(list_of_paths=["chemin/vers/dossier/copies/"])

Je viens de tester le script aujourd'hui avec les premières copies de l'année, je n'ai pas eu de souci...

Pour avoir plus d'informations, il faudrait changer la ligne 100 :

     print(f"ERROR: no files/folders provided"
                           f" neither selected in Nautilus")

par ceci :

     print(f"ERROR: no files/folders provided"
                           f" neither selected in Nautilus\n{e}")

Quelle distribution linux utilisez-vous ?

**Comment by JeromeO** [comment]
Bonjour et merci pour cette réponse. Je ferai un test dans la journée.
J'utilise XUbuntu.


Le 23 septembre 2019 21:47:15 GMT+02:00, remjg <notifications@github.com> a écrit :
>Bonjour !>
>>
>Je me permets une réponse en français. Oui c'est possible et sûrement
>pas très difficile à ajouter. Je peux regarder à la Toussaint. En
>attendant, il faudrait sûrement remplacer à la main à la fin du script
>:>
>>
>    amcsend = AMCtoOwncloud()>
>>
>par :>
>>
>amcsend = AMCtoOwncloud(list_of_paths=["chemin/vers/dossier/copies/"])>
>>
>Je viens de tester le script aujourd'hui avec les premières copies de
>l'année, je n'ai pas eu de souci...>
>>
>Pour avoir plus d'informations, il faudrait changer la ligne 100 :>
>>
>     print(f"ERROR: no files/folders provided">
>                           f" neither selected in Nautilus")>
>>
>par ceci :>
>>
>     print(f"ERROR: no files/folders provided">
>                           f" neither selected in Nautilus\n{e}")>
>>
>Quelle distribution linux utilisez-vous ?>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remjg/AMCtoOwncloud/issues/1#issuecomment-534255229

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by JeromeO** [comment]
Merci pour la réponse. Je me permets de corriger une information au cas où ça servirait à d'autres : la variable `list_of_paths` attend une string et pas une liste et utilise l'instruction `splitlines` pour la transformer en liste. 

J'ai donc remplacé la ligne concernant  amcsend par :
`amcsend = AMCtoOwncloud(list_of_paths="/chemin/vers/copies/")`

Merci beaucoup pour ta réponse.

**Comment by remjg** [comment]
Merci pour la précision, j'avais un doute ;-) J'ai appris Python pour réaliser ce script (et pour le plaisir) mais ça fait un moment, je ne suis plus sûr de rien.
